DROP TABLE IF EXISTS ORDER1;

CREATE TABLE ORDER1 (
  ORDER_ID INT   PRIMARY KEY,	
  CUSTOMER_NAME VARCHAR(250),
  ORDER_DATE DATE,
  SHIPPING_ADDRESS VARCHAR(250) NOT NULL ,
  TOTAL_AMT INT
);
 
INSERT INTO ORDER1 (ORDER_ID, CUSTOMER_NAME, ORDER_DATE, SHIPPING_ADDRESS, TOTAL_AMT) VALUES
  ('1001', 'abc', '2020-01-07', 'hyd', '222');